# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 1.8
    - name: Copy jbmc binary
      run: |
        echo "PATH=$GITHUB_WORKSPACE/JBMCbin" >> $GITHUB_ENV
        chmod +x $GITHUB_WORKSPACE/JBMCbin/jbmc
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4
        arguments: build
