# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 8.0.312+7
    - name: Install cbmc (linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        curl https://github.com/diffblue/cbmc/releases/download/cbmc-5.58.1/ubuntu-20.04-cbmc-5.58.1-Linux.deb -o cbmc.deb -L
        dpkg -i cbmc.deb
    - name: Install cbmc (windows)
      if: matrix.os == 'windows-latest'
      run: |
        curl -L -o cbmc.msi https://github.com/diffblue/cbmc/releases/download/cbmc-5.58.1/cbmc-5.58.1-win64.msi
        msiexec /i cbmc-5.58.1-win64.msi
        PATH="C:\Program Files\cbmc\bin";%PATH%
    - name: Install cbmc (mac)
      if: matrix.os == 'macos_latest'
      run: |
        brew install cbmc
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4
        arguments: build
